name: Code Quality

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  run:
    runs-on: ubuntu-latest
    name: Check code
    strategy:
      matrix:
        php: [ 8.1 ]

    steps:
      - name: Cancel previous runs of this workflow (pull requests only)
        if: ${{ github.event_name == 'pull_request' }}
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none
      
      - name: Install dependencies
        uses: ramsey/composer-install@v2
        with:
          composer-options: "--no-progress"

      - name: Run PHPStan
        # If STEP_DEBUG is enabled, PHPStan will run in debug mode.
        run: |
          if [ "${{ secrets.ACTIONS_STEP_DEBUG }}" = "true" ]; then
            php vendor/bin/phpstan analyse --memory-limit=2G --debug
          else
            composer run-script phpstan
          fi
